apiVersion: v1
kind: ServiceAccount
metadata:
  name: traific-workloads
  namespace: traific-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: traific-workloads-role
  namespace: traific-apps
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traific-workloads-binding
  namespace: traific-apps
subjects:
  - kind: ServiceAccount
    name: traific-workloads
    namespace: traific-apps
roleRef:
  kind: Role
  name: traific-workloads-role
  apiGroup: rbac.authorization.k8s.io
