apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: traific-redis
data:
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfsync everysec
    save ""
    tcp-keepalive 60
    timeout 300
    maxclients 10000
    slowlog-log-slower-than 10000
    slowlog-max-len 128
