apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: traific-redis
  labels:
    app: redis
    app.kubernetes.io/name: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
    - name: redis-sentinel
      port: 26379
      targetPort: 26379
      protocol: TCP
  selector:
    app: redis
    app.kubernetes.io/name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: traific-redis
  labels:
    app: redis
    app.kubernetes.io/name: redis
  annotations:
    service.kubernetes.io/headless: ""
spec:
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: redis-sentinel
      port: 26379
      targetPort: 26379
  selector:
    app: redis
    app.kubernetes.io/name: redis
