apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traific-apps

resources:
  - ../namespaces/00-namespaces.yaml
  - ../mqtt/
  - ../redis/
  - ../api/
  - ../analytics/
  - ../ingress/
  - ./base/resource-quota.yaml
  - ./base/network-policies.yaml
  - ./base/rbac.yaml
  - ./base/storage-class.yaml
